### ISSUE TITLE
是不是写重复了

### ISSUE THREAD

**Issue by xuanhusec** [jweny/pocassist#2]
https://github.com/jweny/pocassist/blob/169c0d0290b209da663fde906c88f8126473443e/cmd/run.go#L32
这个和31行是不是写重复了

**Comment by jweny** [comment]
> https://github.com/jweny/pocassist/blob/169c0d0290b209da663fde906c88f8126473443e/cmd/run.go#L32
> 
> 
> 这个和31行是不是写重复了

是的 感谢提醒 源代码已更新 晚些发布操作手册和新版release
