### ISSUE TITLE
pocassist 第一次运行时demo密码不正确

### ISSUE THREAD

**Issue by immortal-autumn** [jweny/pocassist#20]
按照官方文档提供U/P: admin/admin2无法登录pocassist demo界面

**Comment by jweny** [comment]
下载数据库了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jweny/pocassist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 下午4:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jweny/pocassist] pocassist 第一次运行时demo密码不正确 (#20)





 
按照官方文档提供U/P: admin/admin2无法登录pocassist demo界面

**Comment by immortal-autumn** [comment]
哦哦果然是没下载数据库2333
